//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int booking_id { get; set; }
        public Nullable<int> numtravellers { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> flights_id { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public string from_location { get; set; }
        public string to_location { get; set; }
        public string date { get; set; }
    }
}
