//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class travelstartEntities4 : DbContext
    {
        internal IEnumerable<object> Employe;

        public travelstartEntities4()
            : base("name=travelstartEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employe> Employes { get; set; }

        public System.Data.Entity.DbSet<MyServer.Models.traveller> travellers { get; set; }

        // internal class FirstOrDefault : IDisposable
        //{
        //    private Func<object, object> p;

        //    public FirstOrDefault(Func<object, object> p)
        //    {
        //        this.p = p;
        //    }
        //}
    }
}
