//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flight
    {
        public int flights_Id { get; set; }
        public string flight_Name { get; set; }
        public string from_Location { get; set; }
        public string to_Location { get; set; }
        public System.DateTime departure_Date { get; set; }
        public System.DateTime arrival_Date { get; set; }
        public int total_Seats { get; set; }
        public int available_Seats { get; set; }
        public decimal price { get; set; }
        public Nullable<int> users_userdD { get; set; }
        public Nullable<int> total { get; set; }
    }
}
