//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int payment_id { get; set; }
        public Nullable<int> users_user_id { get; set; }
        public string transaction_date { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> flight_id { get; set; }
        public string from { get; set; }
        public string to { get; set; }
    }
}
