//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class traveller
    {
        public int traveller_id { get; set; }
        public string FisrtName { get; set; }
        public string LastName { get; set; }
        public string typeOfMeal { get; set; }
        public string email { get; set; }
        public string countryCode { get; set; }
        public string number { get; set; }
        public Nullable<int> users_userId { get; set; }
    }
}
